from sqlalchemy import (
    BigInteger,
    Column,
    Date,
    DateTime,
    ForeignKey,
    Numeric,
    String,
)
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func


from database import Base


# Holdings model — mirrors the holdings table in Supabase
class Holding(Base):
    __tablename__ = "holdings"

    # Primary key
    id = Column(
        BigInteger,
        primary_key=True,
        autoincrement=True,
    )

    # Foreign key to portfolios table.
    #
    # One portfolio may contain many holdings, so this column must not
    # have a unique constraint by itself.
    portfolio_id = Column(
        BigInteger,
        ForeignKey(
            "portfolios.id",
            ondelete="CASCADE",
        ),
        nullable=False,
    )

    # Foreign key to stocks table.
    #
    # The related Stock record stores the symbol, company name,
    # native market currency, and latest market price.
    stock_id = Column(
        BigInteger,
        ForeignKey(
            "stocks.id",
            ondelete="CASCADE",
        ),
        nullable=False,
    )

    # Number of shares owned.
    shares = Column(
        Numeric(12, 4),
        nullable=False,
    )

    # Average price paid per share in the currency selected by the user.
    #
    # Example:
    # The user buys AAPL and enters 185.00 EUR per share.
    # In that case:
    #     average_buy_price = 185.00
    #     purchase_currency = "EUR"
    average_buy_price = Column(
        Numeric(12, 2),
        nullable=False,
    )

    # Currency in which the user entered average_buy_price.
    #
    # This is different from the stock's native market currency.
    #
    # Example:
    #     AAPL native currency = USD
    #     User purchase currency = EUR
    purchase_currency = Column(
        String(3),
        nullable=False,
        default="USD",
        server_default="USD",
    )

    # Exchange rate used when the holding was created or updated.
    #
    # Interpretation:
    #     1 purchase_currency =
    #     exchange_rate_at_purchase stock-native currency
    #
    # Example:
    #     1 EUR = 1.08 USD
    #     exchange_rate_at_purchase = 1.08
    exchange_rate_at_purchase = Column(
        Numeric(18, 8),
        nullable=False,
        default=1,
        server_default="1",
    )

    # Average purchase price converted into the stock's native market
    # currency at the time the holding was created or updated.
    #
    # Example:
    #     average_buy_price = 185.00 EUR
    #     exchange_rate_at_purchase = 1.08 EUR→USD
    #
    #     average_buy_price_native = 199.80 USD
    #
    # Saving this value ensures that future gain/loss calculations use
    # the historical purchase conversion rather than today's exchange rate.
    average_buy_price_native = Column(
        Numeric(18, 6),
        nullable=False,
    )

    # Date the stock was purchased.
    purchased_at = Column(
        DateTime(timezone=True),
        nullable=True,
    )

    # Timestamp generated by PostgreSQL when the holding is created.
    created_at = Column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )

    # Relationships
    portfolio = relationship(
        "Portfolio",
        back_populates="holdings",
    )

    stock = relationship(
        "Stock",
        back_populates="holdings",
    )