from sqlalchemy import (
    BigInteger,
    Column,
    DateTime,
    Numeric,
    String,
)
from sqlalchemy.sql import func

from database import Base


class TrendingStock(Base):
    """
    Stores one stock returned by the market-trending provider.

    Every row represents one ticker inside one category for a specific
    provider snapshot.

    Examples of categories:
    - GAINER
    - LOSER
    - ACTIVE

    Multiple snapshots may contain the same ticker because trending
    information changes over time.
    """

    __tablename__ = "trending_stocks"

    # Unique identifier for this stored trending row.
    id = Column(
        BigInteger,
        primary_key=True,
        autoincrement=True,
    )

    # Stock ticker returned by the external provider.
    #
    # Examples:
    # AAPL
    # NVDA
    # TSLA
    ticker = Column(
        String(30),
        nullable=False,
        index=True,
    )

    # Identifies the section in which the stock appeared.
    #
    # Expected values:
    # GAINER
    # LOSER
    # ACTIVE
    category = Column(
        String(20),
        nullable=False,
        index=True,
    )

    # Latest price supplied by the trending endpoint.
    price = Column(
        Numeric(18, 6),
        nullable=False,
    )

    # Absolute price movement supplied by the provider.
    change_amount = Column(
        Numeric(18, 6),
        nullable=False,
    )

    # Percentage movement stored as a numeric value.
    #
    # Example:
    # Provider value: "3.45%"
    # Stored value: 3.4500
    change_percentage = Column(
        Numeric(12, 4),
        nullable=False,
    )

    # Trading volume.
    volume = Column(
        BigInteger,
        nullable=False,
    )

    # Timestamp describing when the provider says the data was updated.
    #
    # This may be null if the provider response does not contain a
    # parseable timestamp.
    provider_updated_at = Column(
        DateTime(timezone=True),
        nullable=True,
    )

    # Unique identifier shared by every row belonging to one fetch.
    #
    # Example:
    # All gainers, losers, and active stocks fetched together receive
    # the same snapshot_id.
    snapshot_id = Column(
        String(36),
        nullable=False,
        index=True,
    )

    # Name of the external provider.
    source = Column(
        String(50),
        nullable=False,
        default="alpha_vantage",
        server_default="alpha_vantage",
    )

    # Timestamp generated by PostgreSQL when this row is inserted.
    created_at = Column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        index=True,
    )